version: "3.9"

services:
  db-service:
    image: postgres:16
    environment:
      POSTGRES_USER: timetable
      POSTGRES_PASSWORD: timetable
      POSTGRES_DB: timetable
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq-service:
    image: rabbitmq:3-management
    networks:
      - backend

  keycloak-service:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db-service
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: timetable
      KC_DB_PASSWORD: timetable
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - backend

  redis-service:
    image: redis:7
    networks:
      - backend

  api-gateway-service:
    build: ./services/api-gateway
    depends_on:
      - timetable-service
      - scheduling-engine-service
    networks:
      - backend
      - frontend

  timetable-service:
    build: ./services/timetable-management-service
    depends_on:
      - db-service
      - keycloak-service
    networks:
      - backend

  scheduling-engine-service:
    build: ./services/scheduling-engine-service
    depends_on:
      - db-service
      - rabbitmq-service
    deploy:
      replicas: 3
    networks:
      - backend

  notifications-service:
    build: ./services/notifications-service
    depends_on:
      - rabbitmq-service
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay
